### ISSUE TITLE
Utilização de text block no projeto

### ISSUE THREAD

**Issue by arthurs159** [LucasSabatini/Bank_Management_System#1]
Como desafio para você, seria legal se você utilizasse o text block no seu projeto nos locais onde existem muitos System.out!!!

**Comment by LucasSabatini** [comment]
> Como desafio para você, seria legal se você utilizasse o text block no seu projeto nos locais onde existem muitos System.out!!!

Cara, aceitei o desafio e fiz de dois modos diferentes. coloquei a maior parte dos prints dentro de Strings no formato do text block e fiz um outro de um modo diferente: adicionei o textblock no return de um método (.getWelcome()).

Se você puder dar uma revisada e me dizer se ficou como imaginava, eu agradeceria!!

**Comment by arthurs159** [comment]
Ficou muito bom Lucas!!!!!
